### ISSUE TITLE
No Thermostat found

### ISSUE THREAD

**Issue by mikihacia** [Skarbo/hass-scinan-thermostat#2]
Hi,

I've run into the problem after the recent api change. My thermostat is not listed anymore, but I've got it in my app.

I've had it running okay on V1.0. It was under the scian api earlier but it seems that it's been transferred to saswell V2 now and no longer visible at home assistant.

This error originated from a custom integration.

Logger: custom_components.scinan_thermostat.api
Source: custom_components/scinan_thermostat/api/__init__.py:329
Integration: Scinan Saswell Thermostat (documentation, issues)
First occurred: 15:34:50 (1 occurrences)
Last logged: 15:34:50

Device list result data did not contain a list of thermostats

**Comment by Skarbo** [comment]
Hi @mikihacia ,

I'm sorry for the late response. You can go back to the old API by enabling advanced mode in your profile settings (Profile ->  Advanced Mode).

Add a new Scinan Hub in integration page and you will see some more settings:
<img width="405" alt="image" src="https://github.com/Skarbo/hass-scinan-thermostat/assets/303525/c1189f87-0334-4f47-b87f-bd47480c951c">

Select API Version: 1.0 and API Domain: Scinan to go back to old API. 
Hopefully this works.

**Comment by mikihacia** [comment]
Hi,

I just spotted the reply.

I'm afraid I cannot go on to the old api as I've had to re-activate my account and it has been transferred to the V2 Saswell domain.

When I've done trace tracking on my phone it looks like it's communicating with the V2 api and I can still see my thermostats.

See the result I'm getting:

> `{"result_code":"0","result_data":[{"devices":[{"about":"Master Bedroom","company_id":"1038","countdown":0,"create_time":1495170737000,"device_module":"WIFI","door_type":1,"gps_name":"","id":"10382435CC050629","mstype":0,"online":"1","public_type":0,"s00":"1689685928312,0,21.4,15.0,0,0,1,1,0,1,05,35","timer":0,"title":"Master Bedroom","type":6,"update_time":1672145350000,"user_id":550062}],"type":6}]}`

The error I've had was like: 'No climate devices found'
