### ISSUE TITLE
md5 signature

### ISSUE THREAD

**Issue by late4marshmellow** [Skarbo/hass-scinan-thermostat#5]
Hi!

Great job with the v2 API!
Since Petter Rud who originally developed the Homey app has quit developing his app, I am now trying to make it work again and stumbled over your work, hope I can use parts of to make my life easier :)

but I don't understand Python well and cant get it right on just how to do the md5 sign. 
what is the parameters your are using to generate the final md5 in the api?

as i see you use app secret in the beginning and end, but what in between leaves med clueless..

tried different variations without luck, this is my latest atempt

appSecret: md5 hash
app_key: 100027
company_id: 1038
imei: 357014732382494
timestamp: yyyy.mm.dd hh.mm.ss
appSecret: md5 hash

Hope you could give me a little insight on that part, thank you! :)

**Comment by Skarbo** [comment]
Hey @late4marshmellow !

Glad you liked it.
At some time I will split out the API to it's own module, which is usually done in these kind of projects.

I don't have much experience with Python myself. Learned it just to write this integration.

The `create_md5_signature` function just concats a string and is then MD5 hashed.

```python
# starts with app secret
signedStr = 'the app secret'

# each key value params added to string, sorted by key
signedStr = signedStr + 'paramKey1' + 'paramValue1'
signedStr = signedStr + 'paramKey2' + 'paramValue2'

# app secret is added again
signedStr = signedStr + 'the app secret'

return hexString(md5(signedStr))
```

Nowadays I guess you can just paste this snippet into ChatGPT and get it to convert it to your preferred language.
And it will explain it better than I can.

```python
import hashlib
import time
import aiohttp


def create_timestamp() -> str:
    """Create timestamp for Scinan request"""
    return time.strftime("%Y-%m-%d %H:%M:%S")


def create_md5_hash(string: str) -> str:
    """Create MD5 hash"""
    return hashlib.md5(string.encode()).hexdigest()


def _create_md5_bytes(string: str) -> bytes:
    """Create MD5 bytes"""
    return hashlib.md5(string.encode('utf-8')).digest()


def _convert_hex_string(bytes_arr: bytes) -> str:
    """Convert bytes array to hex string"""
    string_buffer = ""
    for byte in bytes_arr:
        hex_string = hex(byte & 255)[2:]
        if len(hex_string) == 1:
            string_buffer += "0"
        string_buffer += hex_string
    return string_buffer.upper()


def create_md5_signature(params: dict, app_secret: str) -> str:
    """Create MD5 signature for Scinan v2.0 request"""
    sign = app_secret
    sorted_params = dict(sorted(params.items()))  # have to be sorted

    for key, value in sorted_params.items():
        sign += key
        sign += value
    sign += app_secret

    return _convert_hex_string(_create_md5_bytes(sign))


async def main():
    params = {
        # auth params
        "account": 'user@email.com',
        "password": create_md5_hash('password'),
        # required params
        "app_key": '100027',
        "company_id": '1038',
        "imei": 'a random imei',  # https://dyrk.org/tools/imei/
        "timestamp": create_timestamp(),
        # token: 'token', # not for auth
    }

    params['sign'] = create_md5_signature(params, 'the app secret')

    web_session = aiohttp.ClientSession()
    resp = await web_session.post(
        'https://api.scinan.com/v2.0/user/login',
        params=params,
    )
    data = await resp.json(content_type=None)
    print(data)
```

Hope this helps.

**Comment by late4marshmellow** [comment]
wow, seems that I actually did everything correct in the first place but reading your response made me realize that the md5 of password should be lowercase and sign should be uppercase. 
Thanks for your quick response :)
