### ISSUE TITLE
Registert Thermostat - "already excist" 

### ISSUE THREAD

**Issue by papirhesten** [Skarbo/hass-scinan-thermostat#8]
I try to register my Thermostat through my Thermostat app, but when I try to register one of my Thermostats, the same error message appears "already excists", Even though i havent registered it in my app.

Ive added 3 other Thermostats without any issues.

Ive tried to remove it from the app and reinstalling it several times. When i hold the OK button, it goes into AP mode. As soon as i connect to it and pushes "add" in the app, it goes into WiFi mode, but never connects to the WiFi. It just keeps flasing.

Is it faulty?

**Comment by papirhesten** [comment]
Can anyone help?

**Comment by Skarbo** [comment]
Hey. I can't help with connecting devices to WiFi. You should try to factory reset the thermostat. Check the manual on how to do that.

**Comment by papirhesten** [comment]
And how do you reset this device? This process is not explained in the quickheat Thermostat manual.
